In [1]:
!pip install /home/remi/py_event_studies

Processing /home/remi/py_event_studies
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: joblib<2.0.0,>=1.4.2 in /pyenv/versions/3.10.16/lib/python3.10/site-packages (from py_event_studies==0.2.0) (1.5.0)
Requirement already satisfied: matplotlib<4.0,>=3.8 in /pyenv/versions/3.10.16/lib/python3.10/site-packages (from py_event_studies==0.2.0) (3.10.0)
Requirement already satisfied: numba>=0.60.0 in /pyenv/versions/3.10.16/lib/python3.10/site-packages (from py_event_studies==0.2.0) (0.61.2)
Requirement already satisfied: numpy<3.0,>=1.2 in /pyenv/versions/3.10.16/lib/python3.10/site-packages (from py_event_studies==0.2.0) (2.0.0)
Requirement already satisfied: pandas<3.0.0,>=2.0.0 in /pyenv/versions/3.10.16/lib/python3.10/site-packages (from py_event_studies==0.2.0) (2.2.3)
Requirement already satisfied: pyarrow<18.0.0,>=17.0.0 in /pyenv/versions/3.10.16/lib/python3.10/site-packages (from py_event_studies==0.2.0) (17.0.0)
Requirement already satisfied: scikit-learn<2.0.0,>=1.5.1 in /pyenv/versions/3.10.16/lib/python3.10/site-packages (from py_event_studies==0.2.0) (1.6.1)
Requirement already satisfied: contourpy>=1.0.1 in /pyenv/versions/3.10.16/lib/python3.10/site-packages (from matplotlib<4.0,>=3.8->py_event_studies==0.2.0) (1.3.1)
Requirement already satisfied: cycler>=0.10 in /pyenv/versions/3.10.16/lib/python3.10/site-packages (from matplotlib<4.0,>=3.8->py_event_studies==0.2.0) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /pyenv/versions/3.10.16/lib/python3.10/site-packages (from matplotlib<4.0,>=3.8->py_event_studies==0.2.0) (4.56.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /pyenv/versions/3.10.16/lib/python3.10/site-packages (from matplotlib<4.0,>=3.8->py_event_studies==0.2.0) (1.4.8)
Requirement already satisfied: packaging>=20.0 in /pyenv/versions/3.10.16/lib/python3.10/site-packages (from matplotlib<4.0,>=3.8->py_event_studies==0.2.0) (24.2)
Requirement already satisfied: pillow>=8 in /pyenv/versions/3.10.16/lib/python3.10/site-packages (from matplotlib<4.0,>=3.8->py_event_studies==0.2.0) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in /pyenv/versions/3.10.16/lib/python3.10/site-packages (from matplotlib<4.0,>=3.8->py_event_studies==0.2.0) (3.2.1)
Requirement already satisfied: python-dateutil>=2.7 in /pyenv/versions/3.10.16/lib/python3.10/site-packages (from matplotlib<4.0,>=3.8->py_event_studies==0.2.0) (2.9.0.post0)
Requirement already satisfied: llvmlite<0.45,>=0.44.0dev0 in /pyenv/versions/3.10.16/lib/python3.10/site-packages (from numba>=0.60.0->py_event_studies==0.2.0) (0.44.0)
Requirement already satisfied: pytz>=2020.1 in /pyenv/versions/3.10.16/lib/python3.10/site-packages (from pandas<3.0.0,>=2.0.0->py_event_studies==0.2.0) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /pyenv/versions/3.10.16/lib/python3.10/site-packages (from pandas<3.0.0,>=2.0.0->py_event_studies==0.2.0) (2025.2)
Requirement already satisfied: scipy>=1.6.0 in /pyenv/versions/3.10.16/lib/python3.10/site-packages (from scikit-learn<2.0.0,>=1.5.1->py_event_studies==0.2.0) (1.15.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /pyenv/versions/3.10.16/lib/python3.10/site-packages (from scikit-learn<2.0.0,>=1.5.1->py_event_studies==0.2.0) (3.6.0)
Requirement already satisfied: six>=1.5 in /pyenv/versions/3.10.16/lib/python3.10/site-packages (from python-dateutil>=2.7->matplotlib<4.0,>=3.8->py_event_studies==0.2.0) (1.17.0)
Building wheels for collected packages: py_event_studies
  Building wheel for py_event_studies (pyproject.toml) ... done
  Created wheel for py_event_studies: filename=py_event_studies-0.2.0-py3-none-any.whl size=45490 sha256=2ee89df705e71adba76503f1849c3ed15d4f224f0f7ff52e8b46b83b9c9f2334
  Stored in directory: /tmp/pip-ephem-wheel-cache-o3s474j7/wheels/22/02/d9/e18517984e20a6f819988550f1b1e3268cc626948300fdedec
Successfully built py_event_studies
Installing collected packages: py_event_studies
  Attempting uninstall: py_event_studies
    Found existing installation: py_event_studies 0.2.0
    Uninstalling py_event_studies-0.2.0:
      Successfully uninstalled py_event_studies-0.2.0
Successfully installed py_event_studies-0.2.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.

[notice] A new release of pip is available: 25.0.1 -> 25.1.1
[notice] To update, run: pip install --upgrade pip

In [2]:
import numpy as np
import pandas as pd
from scipy import stats
import os
import time
import py_event_studies as pes
from IPython.display import display

In [3]:
pes.clear_cache() # If you want to clear the cache manually (not necessary, used here for demo and showing usefullness bellows)

Cache cleared successfully.

In [4]:
pes.load_data('../.data/CRSPAllClean.parquet')
pes.load_ff_factors('../.data/FF5.csv')

Loading and preprocessing data from ../.data/CRSPAllClean.parquet
Cached preprocessed data for ../.data/CRSPAllClean.parquet
Using cached data for ../.data/CRSPAllClean.parquet

In [6]:
num_simulation = 1000
num_stock_ptf = 50

valid_dates = pes.api.get_valid_dates()[pes.config.estim_period*2:-pes.config.event_period]
date_and_portfolio = []
while len(date_and_portfolio) < num_simulation:
    event_date = np.random.choice(valid_dates)
    valid_permnos = pes.get_valid_permno_at_date(event_date)
    if len(valid_permnos) >= num_stock_ptf:
        selected_permnos = np.random.choice(valid_permnos, num_stock_ptf, replace=False)
        date_and_portfolio.append([event_date, selected_permnos])

In [9]:
import numpy as np
import pandas as pd
from scipy import stats
import os
import time
import py_event_studies as pes

def run_power_analysis(date_and_portfolio, output_dir="power_analysis"):
    """
    Run power analysis and generate formatted tables and dataframes.
    """
    # Create output directory
    os.makedirs(output_dir, exist_ok=True)
    os.makedirs(f"{output_dir}/latex", exist_ok=True)
    os.makedirs(f"{output_dir}/csv", exist_ok=True)
    
    # Define parameters
    shock_values = [0, -0.05, -0.02, -0.01, -0.005, 0.005, 0.01, 0.02, 0.05]
    shock_labels = [f"{s:.1%}" for s in shock_values]
    
    # Define gamma functions for variance multiplication
    gamma_configs = [
        {"func": lambda shape: np.ones(shape), "label": "γ=1"},
        {"func": lambda shape: np.random.uniform(1, 2, shape), "label": "γ~U[1,2]"},
        {"func": lambda shape: np.random.uniform(1.5, 2.5, shape), "label": "γ~U[1.5,2.5]"},
        {"func": lambda shape: np.random.uniform(2.5, 3.5, shape), "label": "γ~U[2.5,3.5]"}
    ]
    
    # Test statistics to evaluate
    test_types = ["std", "CS", "BMP", "KP"]
    
    # Get current cluster configuration
    cluster_nums = pes.config.cluster_num_list
    print(f"Using clusters: {cluster_nums}")
    
    # Dictionary to map cluster numbers to their indices
    cluster_to_idx = {c_num: idx for idx, c_num in enumerate(cluster_nums)}
    
    # Define models
    base_models = ["Market Model", "FF3", "FF5"]
    cluster_models = []
    
    # Generate cluster models dynamically based on current config
    for c_num in cluster_nums:
        cluster_models.extend([
            f"{c_num} clusters",
            f"{c_num} clusters + FF3", 
            f"{c_num} clusters + FF5"
        ])
    
    all_models = base_models + cluster_models
    num_simulations = len(date_and_portfolio)
    
    # Initialize rejection counters and McNemar pairs
    # Structure: {test_type: {gamma_label: {shock_label: {model: count}}}}
    rejection_counts = {}
    mcnemar_pairs = {}
    
    for test in test_types:
        rejection_counts[test] = {}
        mcnemar_pairs[test] = {}
        
        for gamma in gamma_configs:
            g_label = gamma["label"]
            rejection_counts[test][g_label] = {}
            mcnemar_pairs[test][g_label] = {}
            
            for s_label in shock_labels:
                rejection_counts[test][g_label][s_label] = {model: 0 for model in all_models}
                mcnemar_pairs[test][g_label][s_label] = {model: [] for model in all_models if model != "FF5"}
    
    # Process each simulation
    for sim_idx, (event_date, selected_permnos) in enumerate(date_and_portfolio):
        print(f"Processing simulation {sim_idx+1}/{num_simulations} - Date: {event_date}")

        # Compute baseline results
        baseline_results = pes.compute(event_date, selected_permnos)
        
        # For each gamma value (variance multiplier)
        for gamma in gamma_configs:
            gamma_label = gamma["label"]
            
            # For each shock value
            for s_idx, shock in enumerate(shock_values):
                shock_label = shock_labels[s_idx]
                
                # Create shocked results
                shocked_results = baseline_results.create_shocked_results(
                    shock=shock, 
                    c_vector_generator=gamma["func"]
                )
                
                # Process each test type
                for test in test_types:
                    # Get p-values for this test
                    p_values = getattr(shocked_results, f"{test.lower()}_p_values")
                    
                    # Check FF5 rejection
                    ff5_rejected = p_values.iloc[0, 6] < 0.05
                    
                    # Process standard models
                    if p_values.iloc[0, 4] < 0.05:  # Market Model (index 4)
                        rejection_counts[test][gamma_label][shock_label]["Market Model"] += 1
                        mcnemar_pairs[test][gamma_label][shock_label]["Market Model"].append((ff5_rejected, True))
                    else:
                        mcnemar_pairs[test][gamma_label][shock_label]["Market Model"].append((ff5_rejected, False))
                        
                    if p_values.iloc[0, 5] < 0.05:  # FF3 (index 5)
                        rejection_counts[test][gamma_label][shock_label]["FF3"] += 1
                        mcnemar_pairs[test][gamma_label][shock_label]["FF3"].append((ff5_rejected, True))
                    else:
                        mcnemar_pairs[test][gamma_label][shock_label]["FF3"].append((ff5_rejected, False))
                        
                    if ff5_rejected:  # FF5 (index 6)
                        rejection_counts[test][gamma_label][shock_label]["FF5"] += 1
                    
                    # Process cluster models
                    for c_num in cluster_nums:
                        c_idx = cluster_to_idx[c_num]
                        
                        # Cluster only (index 0)
                        model_name = f"{c_num} clusters"
                        if p_values.iloc[c_idx, 0] < 0.05:
                            rejection_counts[test][gamma_label][shock_label][model_name] += 1
                            mcnemar_pairs[test][gamma_label][shock_label][model_name].append((ff5_rejected, True))
                        else:
                            mcnemar_pairs[test][gamma_label][shock_label][model_name].append((ff5_rejected, False))
                        
                        # Cluster + FF3 (index 2)
                        model_name = f"{c_num} clusters + FF3"
                        if p_values.iloc[c_idx, 2] < 0.05:
                            rejection_counts[test][gamma_label][shock_label][model_name] += 1
                            mcnemar_pairs[test][gamma_label][shock_label][model_name].append((ff5_rejected, True))
                        else:
                            mcnemar_pairs[test][gamma_label][shock_label][model_name].append((ff5_rejected, False))
                        
                        # Cluster + FF5 (index 3)
                        model_name = f"{c_num} clusters + FF5"
                        if p_values.iloc[c_idx, 3] < 0.05:
                            rejection_counts[test][gamma_label][shock_label][model_name] += 1
                            mcnemar_pairs[test][gamma_label][shock_label][model_name].append((ff5_rejected, True))
                        else:
                            mcnemar_pairs[test][gamma_label][shock_label][model_name].append((ff5_rejected, False))
            

    # Calculate rejection rates and create result dataframes
    results = {}
    
    for test in test_types:
        results[test] = {}
        
        for gamma in gamma_configs:
            gamma_label = gamma["label"]
            
            # Create dataframe for this test and gamma
            df = pd.DataFrame(index=all_models, columns=shock_labels)
            
            # Calculate rejection rates
            for shock_label in shock_labels:
                for model in all_models:
                    rejection_rate = rejection_counts[test][gamma_label][shock_label][model] / num_simulations * 100
                    df.loc[model, shock_label] = rejection_rate
            
            results[test][gamma_label] = df
            
            # Save CSV
            csv_path = f"{output_dir}/csv/power_{test}_{gamma_label.replace('=', '').replace('~', '').replace('[', '').replace(']', '').replace(',', '_')}.csv"
            df.to_csv(csv_path)
            
            # Create LaTeX table
            create_power_table(
                test, 
                gamma_label, 
                base_models,
                cluster_models,
                df, 
                mcnemar_pairs[test][gamma_label], 
                num_simulations,
                output_dir
            )
    
    print(f"Analysis complete. Results saved to {output_dir}/")
    return results

def perform_mcnemar_test(pairs, num_simulations):
    """Calculate McNemar's test to determine if a model is better than FF5."""
    if not pairs or len(pairs) < num_simulations * 0.8:  # Need sufficient samples
        return False
        
    # Count contingency table entries
    n11 = sum(1 for x, y in pairs if x and y)      # Both reject
    n12 = sum(1 for x, y in pairs if x and not y)  # FF5 rejects, model doesn't
    n21 = sum(1 for x, y in pairs if not x and y)  # FF5 doesn't, model rejects
    n22 = sum(1 for x, y in pairs if not x and not y)  # Neither rejects
    
    # Skip if no or few disagreements
    if n12 + n21 < 5:
        return False
    
    # Calculate McNemar's statistic with continuity correction
    statistic = ((abs(n12 - n21) - 1)**2) / (n12 + n21)
    p_value = 1 - stats.chi2.cdf(statistic, 1)
    
    # Is the model significantly better? (one-sided test)
    is_better = (p_value < 0.05) and (n21 > n12)
    
    return is_better

def create_power_table(test_type, gamma_label, base_models, cluster_models, 
                      df, mcnemar_pairs, num_simulations, output_dir):
    """Create a LaTeX table for a specific test and gamma value."""
    
    # Create table header
    table = "\\begin{table}[!h]\n"
    table += f"    \\caption{{Type II error rates (power): {gamma_label}}}\n"
    table += "    \\small\n"
    table += "    \\begin{center}\n"
    table += "    \\begin{tabular}{l" + "r" * len(df.columns) + "}\n"
    table += "    \\hline\n"
    table += "\\textit{Abnormal return ($\\delta)$} &  "
    for col in df.columns:
        col_formatted = col.replace('%', '\\%')
        table += f" & \\textit{{{col_formatted}}}"
    table += "\\T\\B\\\\\n"
    table += "    \\hline\n"
        
    # Add base models
    for model in base_models:
        table += f"{model}\t"
        for col in df.columns:
            rate = df.loc[model, col]
            table += f"& {rate:.1f}\\% "
        table += "\\\\\n"
    
    # Add divider
    table += "\\hline\n"
    
    # Add cluster models
    for model in cluster_models:
        table += f"{model}\t"
        for col in df.columns:
            rate = df.loc[model, col]
            
            # Determine if model is significantly better than FF5
            is_better = False
            if col != df.columns[0]:  # Skip the 0 shock value
                pairs = mcnemar_pairs[col].get(model, [])
                is_better = perform_mcnemar_test(pairs, num_simulations)
            
            if is_better:
                table += f"& \\textbf{{{rate:.1f}\\%}} "
            else:
                table += f"& {rate:.1f}\\% "
        table += "\\\\\n"
    
    # Add footer
    table += "\\hline\\\\\n"
    table += "\\multicolumn{" + str(len(df.columns) + 1) + "}{l}{\\itshape Bold face indicates rejection of power equal to FF5 model at the 5\\% level based on McNemar's test}\n"
    table += "    \\end{tabular}\n"
    table += "    \\end{center}\n"
    table += "\\end{table}\n"
    
    # Save the table
    clean_label = gamma_label.replace('=', '').replace('~', '').replace('[', '').replace(']', '').replace(',', '_').replace('.', '_')
    filename = f"{output_dir}/latex/power_table_{test_type}_{clean_label}.tex"
    with open(filename, "w") as f:
        f.write(table)
    
    print(f"Created LaTeX table: {filename}")

# Example of how to run the analysis
# pes.config.cluster_num_list = [15, 45, 50]  # Set desired clusters
# results_df = run_power_analysis(date_and_portfolio)

# Example of how to run the analysis
# pes.config.cluster_num_list = [15, 45, 50]  # Set desired clusters
# results_df = run_power_analysis(date_and_portfolio)
# Configure the clusters you want to analyze
pes.config.cluster_num_list = [5, 10, 15, 20, 25, 30, 35, 40, 50]

# Run the analysis
results_df = run_power_analysis(date_and_portfolio)

# Access specific results (example)
cs_gamma1_results = results_df["CS"]["γ=1"]
print(cs_gamma1_results)

Using clusters: [5, 10, 15, 20, 25, 30, 35, 40, 50]
Processing simulation 1/1000 - Date: 20010831
Processing simulation 2/1000 - Date: 19760225
Processing simulation 3/1000 - Date: 19820329
Processing simulation 4/1000 - Date: 19910717
Processing simulation 5/1000 - Date: 19841011
Processing simulation 6/1000 - Date: 20220516
Processing simulation 7/1000 - Date: 20190514
Processing simulation 8/1000 - Date: 19970625
Processing simulation 9/1000 - Date: 19840315
Processing simulation 10/1000 - Date: 19831205
Processing simulation 11/1000 - Date: 19910510
Processing simulation 12/1000 - Date: 20141224
Processing simulation 13/1000 - Date: 20160411
Processing simulation 14/1000 - Date: 19940801
Processing simulation 15/1000 - Date: 20020710
Processing simulation 16/1000 - Date: 19861204
Processing simulation 17/1000 - Date: 19741223
Processing simulation 18/1000 - Date: 19950703
Processing simulation 19/1000 - Date: 20051129
Processing simulation 20/1000 - Date: 19980205
Processing simulation 21/1000 - Date: 19851114
Processing simulation 22/1000 - Date: 19800609
Processing simulation 23/1000 - Date: 20180814
Processing simulation 24/1000 - Date: 20200714
Processing simulation 25/1000 - Date: 20070411
Processing simulation 26/1000 - Date: 19831012
Processing simulation 27/1000 - Date: 19891212
Processing simulation 28/1000 - Date: 20170926
Processing simulation 29/1000 - Date: 20010824
Processing simulation 30/1000 - Date: 19890515
Processing simulation 31/1000 - Date: 20050412
Processing simulation 32/1000 - Date: 20221025
Processing simulation 33/1000 - Date: 19870814
Processing simulation 34/1000 - Date: 20071206
Processing simulation 35/1000 - Date: 20040702
Processing simulation 36/1000 - Date: 20210928
Processing simulation 37/1000 - Date: 19880615
Processing simulation 38/1000 - Date: 19810512
Processing simulation 39/1000 - Date: 19900924
Processing simulation 40/1000 - Date: 19790717
Processing simulation 41/1000 - Date: 20150422
Processing simulation 42/1000 - Date: 20201008
Processing simulation 43/1000 - Date: 20230522
Processing simulation 44/1000 - Date: 19781206
Processing simulation 45/1000 - Date: 19801106
Processing simulation 46/1000 - Date: 19890418
Processing simulation 47/1000 - Date: 20151215
Processing simulation 48/1000 - Date: 20141120
Processing simulation 49/1000 - Date: 20070625
Processing simulation 50/1000 - Date: 19771017
Processing simulation 51/1000 - Date: 20191024
Processing simulation 52/1000 - Date: 20230222
Processing simulation 53/1000 - Date: 19881007
Processing simulation 54/1000 - Date: 20060901
Processing simulation 55/1000 - Date: 20180720
Processing simulation 56/1000 - Date: 20010123
Processing simulation 57/1000 - Date: 19891124
Processing simulation 58/1000 - Date: 20000313
Processing simulation 59/1000 - Date: 20090114
Processing simulation 60/1000 - Date: 19780120
Processing simulation 61/1000 - Date: 20090211
Processing simulation 62/1000 - Date: 20121231
Processing simulation 63/1000 - Date: 20030304
Processing simulation 64/1000 - Date: 20101220
Processing simulation 65/1000 - Date: 19941212
Processing simulation 66/1000 - Date: 20130805
Processing simulation 67/1000 - Date: 20180430
Processing simulation 68/1000 - Date: 20040621
Processing simulation 69/1000 - Date: 19911009
Processing simulation 70/1000 - Date: 19870113
Processing simulation 71/1000 - Date: 20040330
Processing simulation 72/1000 - Date: 19771121
Processing simulation 73/1000 - Date: 19900524
Processing simulation 74/1000 - Date: 20230712
Processing simulation 75/1000 - Date: 19941026
Processing simulation 76/1000 - Date: 19750602
Processing simulation 77/1000 - Date: 20010601
Processing simulation 78/1000 - Date: 20200512
Processing simulation 79/1000 - Date: 19930902
Processing simulation 80/1000 - Date: 19860320
Processing simulation 81/1000 - Date: 20080902
Processing simulation 82/1000 - Date: 19990310
Processing simulation 83/1000 - Date: 20160718
Processing simulation 84/1000 - Date: 19920701
Processing simulation 85/1000 - Date: 19980505
Processing simulation 86/1000 - Date: 19910123
Processing simulation 87/1000 - Date: 19930312
Processing simulation 88/1000 - Date: 19941011
Processing simulation 89/1000 - Date: 19970313
Processing simulation 90/1000 - Date: 19900420
Processing simulation 91/1000 - Date: 20211202
Processing simulation 92/1000 - Date: 19910312
Processing simulation 93/1000 - Date: 20020717
Processing simulation 94/1000 - Date: 19800819
Processing simulation 95/1000 - Date: 20011128
Processing simulation 96/1000 - Date: 19940502
Processing simulation 97/1000 - Date: 19820813
Processing simulation 98/1000 - Date: 20000724
Processing simulation 99/1000 - Date: 20000301
Processing simulation 100/1000 - Date: 20150105
Processing simulation 101/1000 - Date: 20190109
Processing simulation 102/1000 - Date: 19950413
Processing simulation 103/1000 - Date: 19820819
Processing simulation 104/1000 - Date: 19971222
Processing simulation 105/1000 - Date: 20171201
Processing simulation 106/1000 - Date: 20150120
Processing simulation 107/1000 - Date: 20120627
Processing simulation 108/1000 - Date: 20140311
Processing simulation 109/1000 - Date: 20001226
Processing simulation 110/1000 - Date: 19800604
Processing simulation 111/1000 - Date: 19750730
Processing simulation 112/1000 - Date: 19801112
Processing simulation 113/1000 - Date: 19790914
Processing simulation 114/1000 - Date: 20040809
Processing simulation 115/1000 - Date: 20200526
Processing simulation 116/1000 - Date: 19841214
Processing simulation 117/1000 - Date: 19931201
Processing simulation 118/1000 - Date: 20100317
Processing simulation 119/1000 - Date: 20031231
Processing simulation 120/1000 - Date: 20200110
Processing simulation 121/1000 - Date: 19761014
Processing simulation 122/1000 - Date: 19801216
Processing simulation 123/1000 - Date: 19970228
Processing simulation 124/1000 - Date: 20230616
Processing simulation 125/1000 - Date: 19780510
Processing simulation 126/1000 - Date: 20070226
Processing simulation 127/1000 - Date: 20140219
Processing simulation 128/1000 - Date: 20200130
Processing simulation 129/1000 - Date: 19840529
Processing simulation 130/1000 - Date: 20160613
Processing simulation 131/1000 - Date: 20210413
Processing simulation 132/1000 - Date: 19960822
Processing simulation 133/1000 - Date: 20161018
Processing simulation 134/1000 - Date: 20220121
Processing simulation 135/1000 - Date: 19900426
Processing simulation 136/1000 - Date: 19850315
Processing simulation 137/1000 - Date: 19770203
Processing simulation 138/1000 - Date: 19820107
Processing simulation 139/1000 - Date: 20031217
Processing simulation 140/1000 - Date: 19870601
Processing simulation 141/1000 - Date: 20030805
Processing simulation 142/1000 - Date: 20191118
Processing simulation 143/1000 - Date: 19940317
Processing simulation 144/1000 - Date: 19970117
Processing simulation 145/1000 - Date: 20230501
Processing simulation 146/1000 - Date: 19811214
Processing simulation 147/1000 - Date: 19900110
Processing simulation 148/1000 - Date: 19870413
Processing simulation 149/1000 - Date: 19900726
Processing simulation 150/1000 - Date: 19880518
Processing simulation 151/1000 - Date: 20001130
Processing simulation 152/1000 - Date: 19990719
Processing simulation 153/1000 - Date: 20020926
Processing simulation 154/1000 - Date: 19830902
Processing simulation 155/1000 - Date: 20090610
Processing simulation 156/1000 - Date: 20050928
Processing simulation 157/1000 - Date: 19941228
Processing simulation 158/1000 - Date: 20130426
Processing simulation 159/1000 - Date: 19850821
Processing simulation 160/1000 - Date: 19801226

/pyenv/versions/3.10.16/lib/python3.10/site-packages/numpy/lib/_function_base_impl.py:2922: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/pyenv/versions/3.10.16/lib/python3.10/site-packages/numpy/lib/_function_base_impl.py:2923: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/pyenv/versions/3.10.16/lib/python3.10/site-packages/py_event_studies/_ar_statistic_tests.py:83: RuntimeWarning: invalid value encountered in divide
  event_residual_bar = event_residual / sigma_adj
/pyenv/versions/3.10.16/lib/python3.10/site-packages/py_event_studies/_ar_statistic_tests.py:140: RuntimeWarning: invalid value encountered in divide
  event_residual_bar = event_residual / sigma_adj
/pyenv/versions/3.10.16/lib/python3.10/site-packages/py_event_studies/_ar_statistic_tests.py:83: RuntimeWarning: divide by zero encountered in divide
  event_residual_bar = event_residual / sigma_adj
/pyenv/versions/3.10.16/lib/python3.10/site-packages/numpy/_core/_methods.py:185: RuntimeWarning: invalid value encountered in subtract
  x = asanyarray(arr - arrmean)
/pyenv/versions/3.10.16/lib/python3.10/site-packages/py_event_studies/_ar_statistic_tests.py:140: RuntimeWarning: divide by zero encountered in divide
  event_residual_bar = event_residual / sigma_adj

Processing simulation 161/1000 - Date: 20181024
Processing simulation 162/1000 - Date: 20040714
Processing simulation 163/1000 - Date: 20050615
Processing simulation 164/1000 - Date: 20170103
Processing simulation 165/1000 - Date: 19920312
Processing simulation 166/1000 - Date: 20231113
Processing simulation 167/1000 - Date: 20180801
Processing simulation 168/1000 - Date: 19990303
Processing simulation 169/1000 - Date: 20140908
Processing simulation 170/1000 - Date: 19980306
Processing simulation 171/1000 - Date: 19880315
Processing simulation 172/1000 - Date: 19960118
Processing simulation 173/1000 - Date: 20091008
Processing simulation 174/1000 - Date: 19841115
Processing simulation 175/1000 - Date: 19810407
Processing simulation 176/1000 - Date: 20070205
Processing simulation 177/1000 - Date: 19780105
Processing simulation 178/1000 - Date: 19880106
Processing simulation 179/1000 - Date: 19760202
Processing simulation 180/1000 - Date: 20210715
Processing simulation 181/1000 - Date: 19960422
Processing simulation 182/1000 - Date: 19820910
Processing simulation 183/1000 - Date: 20160415
Processing simulation 184/1000 - Date: 19861028
Processing simulation 185/1000 - Date: 19800422
Processing simulation 186/1000 - Date: 20171013
Processing simulation 187/1000 - Date: 20110623
Processing simulation 188/1000 - Date: 20180808
Processing simulation 189/1000 - Date: 20131107
Processing simulation 190/1000 - Date: 20210326
Processing simulation 191/1000 - Date: 19780217
Processing simulation 192/1000 - Date: 20150312
Processing simulation 193/1000 - Date: 20170615
Processing simulation 194/1000 - Date: 20140730
Processing simulation 195/1000 - Date: 19911004
Processing simulation 196/1000 - Date: 20151112
Processing simulation 197/1000 - Date: 20170927
Processing simulation 198/1000 - Date: 19800930
Processing simulation 199/1000 - Date: 20160609
Processing simulation 200/1000 - Date: 20181107
Processing simulation 201/1000 - Date: 20180320
Processing simulation 202/1000 - Date: 20200602
Processing simulation 203/1000 - Date: 19860811
Processing simulation 204/1000 - Date: 20210806
Processing simulation 205/1000 - Date: 20220516
Processing simulation 206/1000 - Date: 19881111
Processing simulation 207/1000 - Date: 19850103
Processing simulation 208/1000 - Date: 19830407
Processing simulation 209/1000 - Date: 19950928
Processing simulation 210/1000 - Date: 20050202
Processing simulation 211/1000 - Date: 19950505
Processing simulation 212/1000 - Date: 19790705
Processing simulation 213/1000 - Date: 19980402
Processing simulation 214/1000 - Date: 20090128
Processing simulation 215/1000 - Date: 20010518
Processing simulation 216/1000 - Date: 20100405
Processing simulation 217/1000 - Date: 20200227
Processing simulation 218/1000 - Date: 20050113
Processing simulation 219/1000 - Date: 19750616
Processing simulation 220/1000 - Date: 19830504
Processing simulation 221/1000 - Date: 19930309
Processing simulation 222/1000 - Date: 20180425
Processing simulation 223/1000 - Date: 20070706
Processing simulation 224/1000 - Date: 19941011
Processing simulation 225/1000 - Date: 19811208
Processing simulation 226/1000 - Date: 19831110
Processing simulation 227/1000 - Date: 19911016
Processing simulation 228/1000 - Date: 20050914
Processing simulation 229/1000 - Date: 20210111
Processing simulation 230/1000 - Date: 19820924
Processing simulation 231/1000 - Date: 19750505
Processing simulation 232/1000 - Date: 19861217
Processing simulation 233/1000 - Date: 20011105
Processing simulation 234/1000 - Date: 20011129
Processing simulation 235/1000 - Date: 20201209
Processing simulation 236/1000 - Date: 19870513
Processing simulation 237/1000 - Date: 20070319
Processing simulation 238/1000 - Date: 19770420
Processing simulation 239/1000 - Date: 19830706
Processing simulation 240/1000 - Date: 19821124
Processing simulation 241/1000 - Date: 19840413
Processing simulation 242/1000 - Date: 20181219
Processing simulation 243/1000 - Date: 20180202
Processing simulation 244/1000 - Date: 20120208
Processing simulation 245/1000 - Date: 20171218
Processing simulation 246/1000 - Date: 20150803
Processing simulation 247/1000 - Date: 19820408
Processing simulation 248/1000 - Date: 19990208
Processing simulation 249/1000 - Date: 19810209
Processing simulation 250/1000 - Date: 19780522
Processing simulation 251/1000 - Date: 20151102
Processing simulation 252/1000 - Date: 19980810
Processing simulation 253/1000 - Date: 20090417
Processing simulation 254/1000 - Date: 19900823
Processing simulation 255/1000 - Date: 19760520
Processing simulation 256/1000 - Date: 19971010
Processing simulation 257/1000 - Date: 19951227
Processing simulation 258/1000 - Date: 19900321
Processing simulation 259/1000 - Date: 20040408
Processing simulation 260/1000 - Date: 19830602
Processing simulation 261/1000 - Date: 19901224
Processing simulation 262/1000 - Date: 20031203
Processing simulation 263/1000 - Date: 20220310
Processing simulation 264/1000 - Date: 19881221
Processing simulation 265/1000 - Date: 19980723
Processing simulation 266/1000 - Date: 20211026
Processing simulation 267/1000 - Date: 20050509
Processing simulation 268/1000 - Date: 19980806
Processing simulation 269/1000 - Date: 19920131
Processing simulation 270/1000 - Date: 19880322
Processing simulation 271/1000 - Date: 19770509
Processing simulation 272/1000 - Date: 20200501
Processing simulation 273/1000 - Date: 19860514
Processing simulation 274/1000 - Date: 19920910
Processing simulation 275/1000 - Date: 19750317
Processing simulation 276/1000 - Date: 19990408
Processing simulation 277/1000 - Date: 19810320
Processing simulation 278/1000 - Date: 20150611
Processing simulation 279/1000 - Date: 20150406
Processing simulation 280/1000 - Date: 20221221
Processing simulation 281/1000 - Date: 19980209
Processing simulation 282/1000 - Date: 19850522
Processing simulation 283/1000 - Date: 20051129
Processing simulation 284/1000 - Date: 19891102
Processing simulation 285/1000 - Date: 19860120
Processing simulation 286/1000 - Date: 19780223
Processing simulation 287/1000 - Date: 20170905
Processing simulation 288/1000 - Date: 19910502
Processing simulation 289/1000 - Date: 20201209
Processing simulation 290/1000 - Date: 20210802
Processing simulation 291/1000 - Date: 19960510
Processing simulation 292/1000 - Date: 19800211
Processing simulation 293/1000 - Date: 19800613
Processing simulation 294/1000 - Date: 20070504
Processing simulation 295/1000 - Date: 20050502
Processing simulation 296/1000 - Date: 20141031
Processing simulation 297/1000 - Date: 20220315
Processing simulation 298/1000 - Date: 20010516
Processing simulation 299/1000 - Date: 20100518
Processing simulation 300/1000 - Date: 19780901
Processing simulation 301/1000 - Date: 19820420
Processing simulation 302/1000 - Date: 20030523
Processing simulation 303/1000 - Date: 19750905
Processing simulation 304/1000 - Date: 20060411
Processing simulation 305/1000 - Date: 19800207
Processing simulation 306/1000 - Date: 19870423
Processing simulation 307/1000 - Date: 19760929
Processing simulation 308/1000 - Date: 20001124
Processing simulation 309/1000 - Date: 20131129
Processing simulation 310/1000 - Date: 20190417
Processing simulation 311/1000 - Date: 20021216
Processing simulation 312/1000 - Date: 19930812
Processing simulation 313/1000 - Date: 20020114
Processing simulation 314/1000 - Date: 19970825
Processing simulation 315/1000 - Date: 20041026
Processing simulation 316/1000 - Date: 19970102
Processing simulation 317/1000 - Date: 19971118
Processing simulation 318/1000 - Date: 19940311
Processing simulation 319/1000 - Date: 19940823
Processing simulation 320/1000 - Date: 19760414
Processing simulation 321/1000 - Date: 20020507
Processing simulation 322/1000 - Date: 19820503
Processing simulation 323/1000 - Date: 19760929
Processing simulation 324/1000 - Date: 20000121
Processing simulation 325/1000 - Date: 20160915
Processing simulation 326/1000 - Date: 19831122
Processing simulation 327/1000 - Date: 19860219
Processing simulation 328/1000 - Date: 20120221
Processing simulation 329/1000 - Date: 19851230
Processing simulation 330/1000 - Date: 20200714
Processing simulation 331/1000 - Date: 20020607
Processing simulation 332/1000 - Date: 20150929
Processing simulation 333/1000 - Date: 19980616
Processing simulation 334/1000 - Date: 20200804
Processing simulation 335/1000 - Date: 20020405
Processing simulation 336/1000 - Date: 20020626
Processing simulation 337/1000 - Date: 20140929
Processing simulation 338/1000 - Date: 19770218
Processing simulation 339/1000 - Date: 19980817
Processing simulation 340/1000 - Date: 20200813
Processing simulation 341/1000 - Date: 19851025
Processing simulation 342/1000 - Date: 19801211
Processing simulation 343/1000 - Date: 20171205
Processing simulation 344/1000 - Date: 19780403
Processing simulation 345/1000 - Date: 19850731
Processing simulation 346/1000 - Date: 19851016
Processing simulation 347/1000 - Date: 19781114
Processing simulation 348/1000 - Date: 19750122
Processing simulation 349/1000 - Date: 20040202
Processing simulation 350/1000 - Date: 20100506
Processing simulation 351/1000 - Date: 19961030
Processing simulation 352/1000 - Date: 20190520
Processing simulation 353/1000 - Date: 20120120
Processing simulation 354/1000 - Date: 19820818
Processing simulation 355/1000 - Date: 19870902
Processing simulation 356/1000 - Date: 20200828
Processing simulation 357/1000 - Date: 19860623
Processing simulation 358/1000 - Date: 19850115
Processing simulation 359/1000 - Date: 20151001
Processing simulation 360/1000 - Date: 20180322
Processing simulation 361/1000 - Date: 19830718
Processing simulation 362/1000 - Date: 19771214
Processing simulation 363/1000 - Date: 19831227
Processing simulation 364/1000 - Date: 20040706
Processing simulation 365/1000 - Date: 19851115
Processing simulation 366/1000 - Date: 19760122
Processing simulation 367/1000 - Date: 20110803
Processing simulation 368/1000 - Date: 19941115
Processing simulation 369/1000 - Date: 19991025
Processing simulation 370/1000 - Date: 20190102
Processing simulation 371/1000 - Date: 20010508
Processing simulation 372/1000 - Date: 20030415
Processing simulation 373/1000 - Date: 19851209
Processing simulation 374/1000 - Date: 19751226
Processing simulation 375/1000 - Date: 20030908
Processing simulation 376/1000 - Date: 19761105
Processing simulation 377/1000 - Date: 20060814
Processing simulation 378/1000 - Date: 19751029
Processing simulation 379/1000 - Date: 19991231
Processing simulation 380/1000 - Date: 20141208
Processing simulation 381/1000 - Date: 20040505
Processing simulation 382/1000 - Date: 20090220
Processing simulation 383/1000 - Date: 20040923
Processing simulation 384/1000 - Date: 20230227
Processing simulation 385/1000 - Date: 19780113
Processing simulation 386/1000 - Date: 20190726
Processing simulation 387/1000 - Date: 20230613
Processing simulation 388/1000 - Date: 19880413
Processing simulation 389/1000 - Date: 20030509
Processing simulation 390/1000 - Date: 20070209
Processing simulation 391/1000 - Date: 19790801
Processing simulation 392/1000 - Date: 19850716
Processing simulation 393/1000 - Date: 19780901
Processing simulation 394/1000 - Date: 19911211
Processing simulation 395/1000 - Date: 20020201
Processing simulation 396/1000 - Date: 19771104
Processing simulation 397/1000 - Date: 19980717
Processing simulation 398/1000 - Date: 19901010
Processing simulation 399/1000 - Date: 19851011
Processing simulation 400/1000 - Date: 20111109
Processing simulation 401/1000 - Date: 19881230
Processing simulation 402/1000 - Date: 20230828
Processing simulation 403/1000 - Date: 20080807
Processing simulation 404/1000 - Date: 20230613
Processing simulation 405/1000 - Date: 20020822
Processing simulation 406/1000 - Date: 19970314
Processing simulation 407/1000 - Date: 19890322
Processing simulation 408/1000 - Date: 19881007
Processing simulation 409/1000 - Date: 20030225
Processing simulation 410/1000 - Date: 20100818
Processing simulation 411/1000 - Date: 20090622
Processing simulation 412/1000 - Date: 20160913
Processing simulation 413/1000 - Date: 20061129
Processing simulation 414/1000 - Date: 20190222
Processing simulation 415/1000 - Date: 19870714
Processing simulation 416/1000 - Date: 20030102
Processing simulation 417/1000 - Date: 20180925
Processing simulation 418/1000 - Date: 19910422
Processing simulation 419/1000 - Date: 20041126
Processing simulation 420/1000 - Date: 20100430
Processing simulation 421/1000 - Date: 19860613
Processing simulation 422/1000 - Date: 20170531
Processing simulation 423/1000 - Date: 19970612
Processing simulation 424/1000 - Date: 19991119
Processing simulation 425/1000 - Date: 19950426
Processing simulation 426/1000 - Date: 19940715
Processing simulation 427/1000 - Date: 20120227
Processing simulation 428/1000 - Date: 20190711
Processing simulation 429/1000 - Date: 19801031
Processing simulation 430/1000 - Date: 19871210
Processing simulation 431/1000 - Date: 20040213
Processing simulation 432/1000 - Date: 20021105
Processing simulation 433/1000 - Date: 19811228

/pyenv/versions/3.10.16/lib/python3.10/site-packages/numpy/lib/_function_base_impl.py:2922: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/pyenv/versions/3.10.16/lib/python3.10/site-packages/numpy/lib/_function_base_impl.py:2923: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/pyenv/versions/3.10.16/lib/python3.10/site-packages/py_event_studies/_ar_statistic_tests.py:83: RuntimeWarning: invalid value encountered in divide
  event_residual_bar = event_residual / sigma_adj
/pyenv/versions/3.10.16/lib/python3.10/site-packages/py_event_studies/_ar_statistic_tests.py:140: RuntimeWarning: invalid value encountered in divide
  event_residual_bar = event_residual / sigma_adj
/pyenv/versions/3.10.16/lib/python3.10/site-packages/py_event_studies/_ar_statistic_tests.py:83: RuntimeWarning: divide by zero encountered in divide
  event_residual_bar = event_residual / sigma_adj
/pyenv/versions/3.10.16/lib/python3.10/site-packages/numpy/_core/_methods.py:185: RuntimeWarning: invalid value encountered in subtract
  x = asanyarray(arr - arrmean)
/pyenv/versions/3.10.16/lib/python3.10/site-packages/py_event_studies/_ar_statistic_tests.py:140: RuntimeWarning: divide by zero encountered in divide
  event_residual_bar = event_residual / sigma_adj

Processing simulation 434/1000 - Date: 19901016
Processing simulation 435/1000 - Date: 20151006
Processing simulation 436/1000 - Date: 20111019
Processing simulation 437/1000 - Date: 19831201
Processing simulation 438/1000 - Date: 20000515
Processing simulation 439/1000 - Date: 19790920
Processing simulation 440/1000 - Date: 19881220
Processing simulation 441/1000 - Date: 20071206
Processing simulation 442/1000 - Date: 19750918
Processing simulation 443/1000 - Date: 19890103
Processing simulation 444/1000 - Date: 19890419
Processing simulation 445/1000 - Date: 19971124
Processing simulation 446/1000 - Date: 19880914
Processing simulation 447/1000 - Date: 19800318
Processing simulation 448/1000 - Date: 20060622
Processing simulation 449/1000 - Date: 20180906
Processing simulation 450/1000 - Date: 20050331
Processing simulation 451/1000 - Date: 19901115
Processing simulation 452/1000 - Date: 20180123
Processing simulation 453/1000 - Date: 20220609
Processing simulation 454/1000 - Date: 19820223

/pyenv/versions/3.10.16/lib/python3.10/site-packages/numpy/lib/_function_base_impl.py:2922: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/pyenv/versions/3.10.16/lib/python3.10/site-packages/numpy/lib/_function_base_impl.py:2923: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/pyenv/versions/3.10.16/lib/python3.10/site-packages/py_event_studies/_ar_statistic_tests.py:83: RuntimeWarning: invalid value encountered in divide
  event_residual_bar = event_residual / sigma_adj
/pyenv/versions/3.10.16/lib/python3.10/site-packages/py_event_studies/_ar_statistic_tests.py:140: RuntimeWarning: invalid value encountered in divide
  event_residual_bar = event_residual / sigma_adj
/pyenv/versions/3.10.16/lib/python3.10/site-packages/py_event_studies/_ar_statistic_tests.py:83: RuntimeWarning: divide by zero encountered in divide
  event_residual_bar = event_residual / sigma_adj
/pyenv/versions/3.10.16/lib/python3.10/site-packages/numpy/_core/_methods.py:185: RuntimeWarning: invalid value encountered in subtract
  x = asanyarray(arr - arrmean)
/pyenv/versions/3.10.16/lib/python3.10/site-packages/py_event_studies/_ar_statistic_tests.py:140: RuntimeWarning: divide by zero encountered in divide
  event_residual_bar = event_residual / sigma_adj

Processing simulation 455/1000 - Date: 20161014
Processing simulation 456/1000 - Date: 20140916
Processing simulation 457/1000 - Date: 19921120
Processing simulation 458/1000 - Date: 19750826
Processing simulation 459/1000 - Date: 20090924
Processing simulation 460/1000 - Date: 19760319
Processing simulation 461/1000 - Date: 20030206
Processing simulation 462/1000 - Date: 19911011
Processing simulation 463/1000 - Date: 20141008
Processing simulation 464/1000 - Date: 20030311
Processing simulation 465/1000 - Date: 20160526
Processing simulation 466/1000 - Date: 20200616
Processing simulation 467/1000 - Date: 19860716
Processing simulation 468/1000 - Date: 19870826
Processing simulation 469/1000 - Date: 20100816
Processing simulation 470/1000 - Date: 19881024
Processing simulation 471/1000 - Date: 19850409
Processing simulation 472/1000 - Date: 20120319
Processing simulation 473/1000 - Date: 20180604
Processing simulation 474/1000 - Date: 19781024
Processing simulation 475/1000 - Date: 20101105
Processing simulation 476/1000 - Date: 19800624
Processing simulation 477/1000 - Date: 19780612
Processing simulation 478/1000 - Date: 19821026
Processing simulation 479/1000 - Date: 19880610
Processing simulation 480/1000 - Date: 19770928
Processing simulation 481/1000 - Date: 20061115
Processing simulation 482/1000 - Date: 19960617
Processing simulation 483/1000 - Date: 19801203
Processing simulation 484/1000 - Date: 19800616
Processing simulation 485/1000 - Date: 19780627
Processing simulation 486/1000 - Date: 19760123
Processing simulation 487/1000 - Date: 19870324
Processing simulation 488/1000 - Date: 20210818
Processing simulation 489/1000 - Date: 19880509
Processing simulation 490/1000 - Date: 19940131
Processing simulation 491/1000 - Date: 19790221
Processing simulation 492/1000 - Date: 20030804
Processing simulation 493/1000 - Date: 19790404
Processing simulation 494/1000 - Date: 20191010
Processing simulation 495/1000 - Date: 20210908
Processing simulation 496/1000 - Date: 20040929
Processing simulation 497/1000 - Date: 19880322
Processing simulation 498/1000 - Date: 20140606
Processing simulation 499/1000 - Date: 19801208
Processing simulation 500/1000 - Date: 20010712
Processing simulation 501/1000 - Date: 20191226
Processing simulation 502/1000 - Date: 19870826
Processing simulation 503/1000 - Date: 19921215
Processing simulation 504/1000 - Date: 19860818
Processing simulation 505/1000 - Date: 19860219
Processing simulation 506/1000 - Date: 20091110
Processing simulation 507/1000 - Date: 20171102
Processing simulation 508/1000 - Date: 19780720
Processing simulation 509/1000 - Date: 20100713
Processing simulation 510/1000 - Date: 20170321
Processing simulation 511/1000 - Date: 19940201
Processing simulation 512/1000 - Date: 20171030
Processing simulation 513/1000 - Date: 20091106
Processing simulation 514/1000 - Date: 19950616
Processing simulation 515/1000 - Date: 20000328
Processing simulation 516/1000 - Date: 19780310
Processing simulation 517/1000 - Date: 20110708
Processing simulation 518/1000 - Date: 20060331
Processing simulation 519/1000 - Date: 19901022
Processing simulation 520/1000 - Date: 20230119
Processing simulation 521/1000 - Date: 20150122
Processing simulation 522/1000 - Date: 20080512
Processing simulation 523/1000 - Date: 19781215
Processing simulation 524/1000 - Date: 19790307
Processing simulation 525/1000 - Date: 20041022
Processing simulation 526/1000 - Date: 20140911
Processing simulation 527/1000 - Date: 20020125
Processing simulation 528/1000 - Date: 20051214
Processing simulation 529/1000 - Date: 19791212
Processing simulation 530/1000 - Date: 19910628
Processing simulation 531/1000 - Date: 20040311
Processing simulation 532/1000 - Date: 19861031
Processing simulation 533/1000 - Date: 20200225
Processing simulation 534/1000 - Date: 20000327
Processing simulation 535/1000 - Date: 19880812
Processing simulation 536/1000 - Date: 19970418
Processing simulation 537/1000 - Date: 20060725
Processing simulation 538/1000 - Date: 20211213
Processing simulation 539/1000 - Date: 19930212
Processing simulation 540/1000 - Date: 19920727
Processing simulation 541/1000 - Date: 19890123
Processing simulation 542/1000 - Date: 19820219
Processing simulation 543/1000 - Date: 20190625
Processing simulation 544/1000 - Date: 19810910
Processing simulation 545/1000 - Date: 19890131
Processing simulation 546/1000 - Date: 20020404
Processing simulation 547/1000 - Date: 19801031
Processing simulation 548/1000 - Date: 19750312
Processing simulation 549/1000 - Date: 20111221
Processing simulation 550/1000 - Date: 20200519
Processing simulation 551/1000 - Date: 20180131
Processing simulation 552/1000 - Date: 20160621
Processing simulation 553/1000 - Date: 20211008
Processing simulation 554/1000 - Date: 19930222
Processing simulation 555/1000 - Date: 20191230
Processing simulation 556/1000 - Date: 19841029
Processing simulation 557/1000 - Date: 20090318
Processing simulation 558/1000 - Date: 20220310
Processing simulation 559/1000 - Date: 19910508
Processing simulation 560/1000 - Date: 19920824
Processing simulation 561/1000 - Date: 19871116
Processing simulation 562/1000 - Date: 20120816
Processing simulation 563/1000 - Date: 20131231
Processing simulation 564/1000 - Date: 19850402
Processing simulation 565/1000 - Date: 20210903
Processing simulation 566/1000 - Date: 20030903
Processing simulation 567/1000 - Date: 20000907
Processing simulation 568/1000 - Date: 20090608
Processing simulation 569/1000 - Date: 20020827
Processing simulation 570/1000 - Date: 20060810
Processing simulation 571/1000 - Date: 19930624
Processing simulation 572/1000 - Date: 19960223
Processing simulation 573/1000 - Date: 20120301
Processing simulation 574/1000 - Date: 20221107
Processing simulation 575/1000 - Date: 19871119
Processing simulation 576/1000 - Date: 19851202
Processing simulation 577/1000 - Date: 20140205
Processing simulation 578/1000 - Date: 19880817
Processing simulation 579/1000 - Date: 19900824
Processing simulation 580/1000 - Date: 19850806
Processing simulation 581/1000 - Date: 19850709
Processing simulation 582/1000 - Date: 20010302
Processing simulation 583/1000 - Date: 20070618
Processing simulation 584/1000 - Date: 20191115
Processing simulation 585/1000 - Date: 20230829
Processing simulation 586/1000 - Date: 20100901
Processing simulation 587/1000 - Date: 20090318
Processing simulation 588/1000 - Date: 19941026
Processing simulation 589/1000 - Date: 19881111
Processing simulation 590/1000 - Date: 19971008
Processing simulation 591/1000 - Date: 19800624
Processing simulation 592/1000 - Date: 20130215
Processing simulation 593/1000 - Date: 19921127
Processing simulation 594/1000 - Date: 20150722
Processing simulation 595/1000 - Date: 19830425
Processing simulation 596/1000 - Date: 20150612
Processing simulation 597/1000 - Date: 19791003
Processing simulation 598/1000 - Date: 19800904
Processing simulation 599/1000 - Date: 19760914
Processing simulation 600/1000 - Date: 19921103
Processing simulation 601/1000 - Date: 20030303
Processing simulation 602/1000 - Date: 19910226
Processing simulation 603/1000 - Date: 20080715
Processing simulation 604/1000 - Date: 20030813
Processing simulation 605/1000 - Date: 19800918
Processing simulation 606/1000 - Date: 20171024
Processing simulation 607/1000 - Date: 19920130
Processing simulation 608/1000 - Date: 19901113
Processing simulation 609/1000 - Date: 20081007
Processing simulation 610/1000 - Date: 19990309
Processing simulation 611/1000 - Date: 20070807
Processing simulation 612/1000 - Date: 20030814
Processing simulation 613/1000 - Date: 20200714
Processing simulation 614/1000 - Date: 20040312
Processing simulation 615/1000 - Date: 20180426
Processing simulation 616/1000 - Date: 20001222
Processing simulation 617/1000 - Date: 19851121
Processing simulation 618/1000 - Date: 19751119
Processing simulation 619/1000 - Date: 20080918
Processing simulation 620/1000 - Date: 20170828
Processing simulation 621/1000 - Date: 19961003
Processing simulation 622/1000 - Date: 19860120
Processing simulation 623/1000 - Date: 20140627
Processing simulation 624/1000 - Date: 19810107
Processing simulation 625/1000 - Date: 20030116
Processing simulation 626/1000 - Date: 19870917
Processing simulation 627/1000 - Date: 20180425
Processing simulation 628/1000 - Date: 20080116
Processing simulation 629/1000 - Date: 20020924
Processing simulation 630/1000 - Date: 20040521
Processing simulation 631/1000 - Date: 20110629
Processing simulation 632/1000 - Date: 19811218
Processing simulation 633/1000 - Date: 19780214
Processing simulation 634/1000 - Date: 20230302
Processing simulation 635/1000 - Date: 20200505
Processing simulation 636/1000 - Date: 20050712
Processing simulation 637/1000 - Date: 20120917
Processing simulation 638/1000 - Date: 20180109
Processing simulation 639/1000 - Date: 19800307
Processing simulation 640/1000 - Date: 20221128
Processing simulation 641/1000 - Date: 19811109
Processing simulation 642/1000 - Date: 19920103
Processing simulation 643/1000 - Date: 20170207
Processing simulation 644/1000 - Date: 19830715
Processing simulation 645/1000 - Date: 20160412
Processing simulation 646/1000 - Date: 20011109
Processing simulation 647/1000 - Date: 20130104
Processing simulation 648/1000 - Date: 19980325
Processing simulation 649/1000 - Date: 20171130
Processing simulation 650/1000 - Date: 20001024
Processing simulation 651/1000 - Date: 20010827
Processing simulation 652/1000 - Date: 20140929
Processing simulation 653/1000 - Date: 19970804
Processing simulation 654/1000 - Date: 19850611
Processing simulation 655/1000 - Date: 20230613
Processing simulation 656/1000 - Date: 19820525
Processing simulation 657/1000 - Date: 19930910
Processing simulation 658/1000 - Date: 19750815
Processing simulation 659/1000 - Date: 19910131
Processing simulation 660/1000 - Date: 19910530
Processing simulation 661/1000 - Date: 19910405
Processing simulation 662/1000 - Date: 20061221
Processing simulation 663/1000 - Date: 20090727
Processing simulation 664/1000 - Date: 19760301
Processing simulation 665/1000 - Date: 19760528
Processing simulation 666/1000 - Date: 20181128
Processing simulation 667/1000 - Date: 20010606
Processing simulation 668/1000 - Date: 19830517
Processing simulation 669/1000 - Date: 19800731
Processing simulation 670/1000 - Date: 20210625
Processing simulation 671/1000 - Date: 20140516
Processing simulation 672/1000 - Date: 19840820
Processing simulation 673/1000 - Date: 19971125
Processing simulation 674/1000 - Date: 19980819
Processing simulation 675/1000 - Date: 20190712
Processing simulation 676/1000 - Date: 19950518
Processing simulation 677/1000 - Date: 20230331
Processing simulation 678/1000 - Date: 20071002
Processing simulation 679/1000 - Date: 19750718
Processing simulation 680/1000 - Date: 19860418
Processing simulation 681/1000 - Date: 20030725
Processing simulation 682/1000 - Date: 19880212
Processing simulation 683/1000 - Date: 20040303
Processing simulation 684/1000 - Date: 19890126
Processing simulation 685/1000 - Date: 19910913
Processing simulation 686/1000 - Date: 19990825
Processing simulation 687/1000 - Date: 19860306
Processing simulation 688/1000 - Date: 20070927
Processing simulation 689/1000 - Date: 20131210
Processing simulation 690/1000 - Date: 20050803
Processing simulation 691/1000 - Date: 20060710
Processing simulation 692/1000 - Date: 20061207
Processing simulation 693/1000 - Date: 20140131
Processing simulation 694/1000 - Date: 20051123
Processing simulation 695/1000 - Date: 20231116
Processing simulation 696/1000 - Date: 19951205
Processing simulation 697/1000 - Date: 19891222
Processing simulation 698/1000 - Date: 19870630
Processing simulation 699/1000 - Date: 19890217
Processing simulation 700/1000 - Date: 20140826
Processing simulation 701/1000 - Date: 19990520
Processing simulation 702/1000 - Date: 20210210
Processing simulation 703/1000 - Date: 20100810
Processing simulation 704/1000 - Date: 19781019
Processing simulation 705/1000 - Date: 20030716
Processing simulation 706/1000 - Date: 20050628
Processing simulation 707/1000 - Date: 19970214
Processing simulation 708/1000 - Date: 19980204
Processing simulation 709/1000 - Date: 19870609
Processing simulation 710/1000 - Date: 19921218
Processing simulation 711/1000 - Date: 19781018
Processing simulation 712/1000 - Date: 20111221
Processing simulation 713/1000 - Date: 19890914
Processing simulation 714/1000 - Date: 19911217
Processing simulation 715/1000 - Date: 20160315
Processing simulation 716/1000 - Date: 19980921
Processing simulation 717/1000 - Date: 19931201
Processing simulation 718/1000 - Date: 20220113
Processing simulation 719/1000 - Date: 19910215
Processing simulation 720/1000 - Date: 20111109
Processing simulation 721/1000 - Date: 20230921
Processing simulation 722/1000 - Date: 19890816
Processing simulation 723/1000 - Date: 19780822
Processing simulation 724/1000 - Date: 20171208
Processing simulation 725/1000 - Date: 19830425
Processing simulation 726/1000 - Date: 19810407
Processing simulation 727/1000 - Date: 19930224
Processing simulation 728/1000 - Date: 20060330
Processing simulation 729/1000 - Date: 20100409
Processing simulation 730/1000 - Date: 19920819
Processing simulation 731/1000 - Date: 19850621
Processing simulation 732/1000 - Date: 19840413
Processing simulation 733/1000 - Date: 19851029
Processing simulation 734/1000 - Date: 20080626
Processing simulation 735/1000 - Date: 19920914
Processing simulation 736/1000 - Date: 19901120
Processing simulation 737/1000 - Date: 20101005
Processing simulation 738/1000 - Date: 19811210
Processing simulation 739/1000 - Date: 20020613
Processing simulation 740/1000 - Date: 19770711
Processing simulation 741/1000 - Date: 19921228
Processing simulation 742/1000 - Date: 19950519
Processing simulation 743/1000 - Date: 19880916
Processing simulation 744/1000 - Date: 19890109
Processing simulation 745/1000 - Date: 19830209
Processing simulation 746/1000 - Date: 20031118
Processing simulation 747/1000 - Date: 19920630
Processing simulation 748/1000 - Date: 19800819
Processing simulation 749/1000 - Date: 19900412
Processing simulation 750/1000 - Date: 19960924
Processing simulation 751/1000 - Date: 20130823
Processing simulation 752/1000 - Date: 19890317
Processing simulation 753/1000 - Date: 20210818
Processing simulation 754/1000 - Date: 19750829
Processing simulation 755/1000 - Date: 19940511
Processing simulation 756/1000 - Date: 19870128
Processing simulation 757/1000 - Date: 20160504
Processing simulation 758/1000 - Date: 19750121
Processing simulation 759/1000 - Date: 19820225
Processing simulation 760/1000 - Date: 19930204
Processing simulation 761/1000 - Date: 20010813
Processing simulation 762/1000 - Date: 19890614
Processing simulation 763/1000 - Date: 20140519
Processing simulation 764/1000 - Date: 19980218
Processing simulation 765/1000 - Date: 19830718
Processing simulation 766/1000 - Date: 19840426
Processing simulation 767/1000 - Date: 19861128
Processing simulation 768/1000 - Date: 19910627
Processing simulation 769/1000 - Date: 20120426
Processing simulation 770/1000 - Date: 20200330
Processing simulation 771/1000 - Date: 19980831
Processing simulation 772/1000 - Date: 19870910
Processing simulation 773/1000 - Date: 20201015
Processing simulation 774/1000 - Date: 19791228
Processing simulation 775/1000 - Date: 19851120
Processing simulation 776/1000 - Date: 19891116
Processing simulation 777/1000 - Date: 19890323
Processing simulation 778/1000 - Date: 19970117
Processing simulation 779/1000 - Date: 19780417
Processing simulation 780/1000 - Date: 20211119
Processing simulation 781/1000 - Date: 19760629
Processing simulation 782/1000 - Date: 19870825
Processing simulation 783/1000 - Date: 20050211
Processing simulation 784/1000 - Date: 19780629
Processing simulation 785/1000 - Date: 19750728
Processing simulation 786/1000 - Date: 19900322
Processing simulation 787/1000 - Date: 19831024
Processing simulation 788/1000 - Date: 19951222
Processing simulation 789/1000 - Date: 19970203
Processing simulation 790/1000 - Date: 20110127
Processing simulation 791/1000 - Date: 20000630
Processing simulation 792/1000 - Date: 20221212
Processing simulation 793/1000 - Date: 19770315
Processing simulation 794/1000 - Date: 19951219
Processing simulation 795/1000 - Date: 20051215
Processing simulation 796/1000 - Date: 20010312
Processing simulation 797/1000 - Date: 19810527
Processing simulation 798/1000 - Date: 20150813
Processing simulation 799/1000 - Date: 20020906
Processing simulation 800/1000 - Date: 19781212
Processing simulation 801/1000 - Date: 20080922
Processing simulation 802/1000 - Date: 19931108
Processing simulation 803/1000 - Date: 20030715
Processing simulation 804/1000 - Date: 20010206
Processing simulation 805/1000 - Date: 19990426
Processing simulation 806/1000 - Date: 20140521
Processing simulation 807/1000 - Date: 20091015
Processing simulation 808/1000 - Date: 20220915
Processing simulation 809/1000 - Date: 19941219
Processing simulation 810/1000 - Date: 20161026
Processing simulation 811/1000 - Date: 19880523
Processing simulation 812/1000 - Date: 20131010
Processing simulation 813/1000 - Date: 20130621
Processing simulation 814/1000 - Date: 20081021
Processing simulation 815/1000 - Date: 19940602
Processing simulation 816/1000 - Date: 20211220
Processing simulation 817/1000 - Date: 20070404
Processing simulation 818/1000 - Date: 20220131
Processing simulation 819/1000 - Date: 20130821
Processing simulation 820/1000 - Date: 19811012
Processing simulation 821/1000 - Date: 19910506
Processing simulation 822/1000 - Date: 20060713
Processing simulation 823/1000 - Date: 20220504
Processing simulation 824/1000 - Date: 20040430
Processing simulation 825/1000 - Date: 19770902
Processing simulation 826/1000 - Date: 20050317
Processing simulation 827/1000 - Date: 19801111
Processing simulation 828/1000 - Date: 20070706
Processing simulation 829/1000 - Date: 19960228
Processing simulation 830/1000 - Date: 19790703
Processing simulation 831/1000 - Date: 20220209
Processing simulation 832/1000 - Date: 19951221
Processing simulation 833/1000 - Date: 20050912
Processing simulation 834/1000 - Date: 20160129
Processing simulation 835/1000 - Date: 19800423
Processing simulation 836/1000 - Date: 19770318
Processing simulation 837/1000 - Date: 20130528
Processing simulation 838/1000 - Date: 19810213

/pyenv/versions/3.10.16/lib/python3.10/site-packages/numpy/lib/_function_base_impl.py:2922: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/pyenv/versions/3.10.16/lib/python3.10/site-packages/numpy/lib/_function_base_impl.py:2923: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/pyenv/versions/3.10.16/lib/python3.10/site-packages/py_event_studies/_ar_statistic_tests.py:83: RuntimeWarning: invalid value encountered in divide
  event_residual_bar = event_residual / sigma_adj
/pyenv/versions/3.10.16/lib/python3.10/site-packages/py_event_studies/_ar_statistic_tests.py:140: RuntimeWarning: invalid value encountered in divide
  event_residual_bar = event_residual / sigma_adj
/pyenv/versions/3.10.16/lib/python3.10/site-packages/py_event_studies/_ar_statistic_tests.py:83: RuntimeWarning: divide by zero encountered in divide
  event_residual_bar = event_residual / sigma_adj
/pyenv/versions/3.10.16/lib/python3.10/site-packages/numpy/_core/_methods.py:185: RuntimeWarning: invalid value encountered in subtract
  x = asanyarray(arr - arrmean)
/pyenv/versions/3.10.16/lib/python3.10/site-packages/py_event_studies/_ar_statistic_tests.py:140: RuntimeWarning: divide by zero encountered in divide
  event_residual_bar = event_residual / sigma_adj

Processing simulation 839/1000 - Date: 19960425
Processing simulation 840/1000 - Date: 20000711
Processing simulation 841/1000 - Date: 20141014
Processing simulation 842/1000 - Date: 19871105
Processing simulation 843/1000 - Date: 20021105
Processing simulation 844/1000 - Date: 20000131
Processing simulation 845/1000 - Date: 20000504
Processing simulation 846/1000 - Date: 20151106
Processing simulation 847/1000 - Date: 19841108
Processing simulation 848/1000 - Date: 20180123
Processing simulation 849/1000 - Date: 19800616
Processing simulation 850/1000 - Date: 20201211
Processing simulation 851/1000 - Date: 20150624
Processing simulation 852/1000 - Date: 19950828
Processing simulation 853/1000 - Date: 20161003
Processing simulation 854/1000 - Date: 19801223
Processing simulation 855/1000 - Date: 20161017
Processing simulation 856/1000 - Date: 19840216
Processing simulation 857/1000 - Date: 19911119
Processing simulation 858/1000 - Date: 19790828
Processing simulation 859/1000 - Date: 19840731
Processing simulation 860/1000 - Date: 19930601
Processing simulation 861/1000 - Date: 20080416
Processing simulation 862/1000 - Date: 19950208
Processing simulation 863/1000 - Date: 19890301
Processing simulation 864/1000 - Date: 19910114
Processing simulation 865/1000 - Date: 20230330
Processing simulation 866/1000 - Date: 19891002
Processing simulation 867/1000 - Date: 20190614
Processing simulation 868/1000 - Date: 20010112
Processing simulation 869/1000 - Date: 20231205
Processing simulation 870/1000 - Date: 20080527
Processing simulation 871/1000 - Date: 19791105
Processing simulation 872/1000 - Date: 19890824
Processing simulation 873/1000 - Date: 19780515
Processing simulation 874/1000 - Date: 19850416
Processing simulation 875/1000 - Date: 20210903
Processing simulation 876/1000 - Date: 19840117
Processing simulation 877/1000 - Date: 20130521
Processing simulation 878/1000 - Date: 19951027
Processing simulation 879/1000 - Date: 19770504
Processing simulation 880/1000 - Date: 19840409
Processing simulation 881/1000 - Date: 20191106
Processing simulation 882/1000 - Date: 20200313
Processing simulation 883/1000 - Date: 20201002
Processing simulation 884/1000 - Date: 20061009
Processing simulation 885/1000 - Date: 19760923
Processing simulation 886/1000 - Date: 19920115
Processing simulation 887/1000 - Date: 20140210
Processing simulation 888/1000 - Date: 19870313
Processing simulation 889/1000 - Date: 20180830
Processing simulation 890/1000 - Date: 19861029
Processing simulation 891/1000 - Date: 19871214
Processing simulation 892/1000 - Date: 20030422
Processing simulation 893/1000 - Date: 20021122
Processing simulation 894/1000 - Date: 19880721
Processing simulation 895/1000 - Date: 20220816
Processing simulation 896/1000 - Date: 19810224
Processing simulation 897/1000 - Date: 20100315
Processing simulation 898/1000 - Date: 20100702
Processing simulation 899/1000 - Date: 20190517
Processing simulation 900/1000 - Date: 20141203
Processing simulation 901/1000 - Date: 20100112
Processing simulation 902/1000 - Date: 19850702
Processing simulation 903/1000 - Date: 19950809
Processing simulation 904/1000 - Date: 20230210
Processing simulation 905/1000 - Date: 20190823
Processing simulation 906/1000 - Date: 20200131
Processing simulation 907/1000 - Date: 19890824
Processing simulation 908/1000 - Date: 20161207
Processing simulation 909/1000 - Date: 19931004
Processing simulation 910/1000 - Date: 19960917
Processing simulation 911/1000 - Date: 20040218
Processing simulation 912/1000 - Date: 19871222
Processing simulation 913/1000 - Date: 19881205
Processing simulation 914/1000 - Date: 19940315
Processing simulation 915/1000 - Date: 20111010
Processing simulation 916/1000 - Date: 20050412
Processing simulation 917/1000 - Date: 20031126
Processing simulation 918/1000 - Date: 20190315
Processing simulation 919/1000 - Date: 19820205
Processing simulation 920/1000 - Date: 20110912
Processing simulation 921/1000 - Date: 20130806
Processing simulation 922/1000 - Date: 19871106
Processing simulation 923/1000 - Date: 19751028
Processing simulation 924/1000 - Date: 19750829
Processing simulation 925/1000 - Date: 19860723
Processing simulation 926/1000 - Date: 20210319
Processing simulation 927/1000 - Date: 19860226
Processing simulation 928/1000 - Date: 20020104
Processing simulation 929/1000 - Date: 20121025
Processing simulation 930/1000 - Date: 19990127
Processing simulation 931/1000 - Date: 19870825
Processing simulation 932/1000 - Date: 20050809
Processing simulation 933/1000 - Date: 19950823
Processing simulation 934/1000 - Date: 19830203
Processing simulation 935/1000 - Date: 19911217
Processing simulation 936/1000 - Date: 19920622
Processing simulation 937/1000 - Date: 19861003
Processing simulation 938/1000 - Date: 20030611
Processing simulation 939/1000 - Date: 20000321
Processing simulation 940/1000 - Date: 19870507
Processing simulation 941/1000 - Date: 19780526
Processing simulation 942/1000 - Date: 20150316
Processing simulation 943/1000 - Date: 20071009
Processing simulation 944/1000 - Date: 19850819
Processing simulation 945/1000 - Date: 20190724
Processing simulation 946/1000 - Date: 19970303
Processing simulation 947/1000 - Date: 19900103
Processing simulation 948/1000 - Date: 20160923
Processing simulation 949/1000 - Date: 19860619
Processing simulation 950/1000 - Date: 19911002
Processing simulation 951/1000 - Date: 19880815
Processing simulation 952/1000 - Date: 19781101
Processing simulation 953/1000 - Date: 20180518
Processing simulation 954/1000 - Date: 19961205
Processing simulation 955/1000 - Date: 20110928
Processing simulation 956/1000 - Date: 20131016
Processing simulation 957/1000 - Date: 19790131
Processing simulation 958/1000 - Date: 20220916
Processing simulation 959/1000 - Date: 20020515
Processing simulation 960/1000 - Date: 19761029
Processing simulation 961/1000 - Date: 20120918
Processing simulation 962/1000 - Date: 19871019
Processing simulation 963/1000 - Date: 19811216
Processing simulation 964/1000 - Date: 19840703
Processing simulation 965/1000 - Date: 20110331
Processing simulation 966/1000 - Date: 19860718
Processing simulation 967/1000 - Date: 19850605
Processing simulation 968/1000 - Date: 20091203
Processing simulation 969/1000 - Date: 20081006
Processing simulation 970/1000 - Date: 20120319
Processing simulation 971/1000 - Date: 19750521
Processing simulation 972/1000 - Date: 20170510
Processing simulation 973/1000 - Date: 19780825
Processing simulation 974/1000 - Date: 19930203
Processing simulation 975/1000 - Date: 19790426
Processing simulation 976/1000 - Date: 20001226
Processing simulation 977/1000 - Date: 19840222
Processing simulation 978/1000 - Date: 19831026
Processing simulation 979/1000 - Date: 19860409
Processing simulation 980/1000 - Date: 19750129
Processing simulation 981/1000 - Date: 20020128
Processing simulation 982/1000 - Date: 19770104
Processing simulation 983/1000 - Date: 20010605
Processing simulation 984/1000 - Date: 19760331
Processing simulation 985/1000 - Date: 19940526
Processing simulation 986/1000 - Date: 19750113
Processing simulation 987/1000 - Date: 20110314
Processing simulation 988/1000 - Date: 19791128
Processing simulation 989/1000 - Date: 20090724
Processing simulation 990/1000 - Date: 19921022
Processing simulation 991/1000 - Date: 19790724
Processing simulation 992/1000 - Date: 19780615
Processing simulation 993/1000 - Date: 20051004
Processing simulation 994/1000 - Date: 20060530
Processing simulation 995/1000 - Date: 20131011
Processing simulation 996/1000 - Date: 19801230
Processing simulation 997/1000 - Date: 20100301
Processing simulation 998/1000 - Date: 19920312
Processing simulation 999/1000 - Date: 20070709
Processing simulation 1000/1000 - Date: 19880201
Created LaTeX table: power_analysis/latex/power_table_std_γ1.tex
Created LaTeX table: power_analysis/latex/power_table_std_γU1_2.tex
Created LaTeX table: power_analysis/latex/power_table_std_γU1_5_2_5.tex
Created LaTeX table: power_analysis/latex/power_table_std_γU2_5_3_5.tex
Created LaTeX table: power_analysis/latex/power_table_CS_γ1.tex
Created LaTeX table: power_analysis/latex/power_table_CS_γU1_2.tex
Created LaTeX table: power_analysis/latex/power_table_CS_γU1_5_2_5.tex
Created LaTeX table: power_analysis/latex/power_table_CS_γU2_5_3_5.tex
Created LaTeX table: power_analysis/latex/power_table_BMP_γ1.tex
Created LaTeX table: power_analysis/latex/power_table_BMP_γU1_2.tex
Created LaTeX table: power_analysis/latex/power_table_BMP_γU1_5_2_5.tex
Created LaTeX table: power_analysis/latex/power_table_BMP_γU2_5_3_5.tex
Created LaTeX table: power_analysis/latex/power_table_KP_γ1.tex
Created LaTeX table: power_analysis/latex/power_table_KP_γU1_2.tex
Created LaTeX table: power_analysis/latex/power_table_KP_γU1_5_2_5.tex
Created LaTeX table: power_analysis/latex/power_table_KP_γU2_5_3_5.tex
Analysis complete. Results saved to power_analysis/
                   0.0% -5.0% -2.0% -1.0% -0.5%  0.5%  1.0%  2.0%   5.0%
Market Model       13.2  99.8  93.1  66.4  34.0  30.2  62.9  95.0   99.9
FF3                 5.2  99.7  94.9  70.3  30.8  24.3  64.6  96.1   99.9
FF5                 5.2  99.7  94.7  69.8  30.6  25.0  64.4  96.0   99.9
5 clusters          4.7  99.7  94.8  70.7  31.6  25.2  65.4  96.5  100.0
5 clusters + FF3    4.2  99.7  94.5  70.7  30.4  23.8  65.4  96.2  100.0
5 clusters + FF5    4.0  99.7  94.7  70.1  30.5  23.6  65.2  96.1  100.0
10 clusters         4.7  99.7  94.9  71.2  31.4  24.7  65.2  96.6  100.0
10 clusters + FF3   4.6  99.7  94.9  70.8  30.4  23.4  65.4  96.6  100.0
10 clusters + FF5   4.2  99.7  94.8  69.9  30.7  23.7  65.0  96.4  100.0
15 clusters         4.5  99.7  95.0  70.5  31.7  24.8  65.3  96.9  100.0
15 clusters + FF3   4.1  99.7  94.8  70.5  30.6  23.9  65.4  96.4  100.0
15 clusters + FF5   4.2  99.7  94.6  70.4  30.9  23.8  64.7  96.3  100.0
20 clusters         4.1  99.7  94.9  70.9  31.8  23.8  65.7  96.9  100.0
20 clusters + FF3   3.9  99.7  94.7  70.8  30.2  24.2  65.5  96.6  100.0
20 clusters + FF5   3.7  99.7  94.7  70.1  30.4  24.4  64.7  96.8  100.0
25 clusters         4.9  99.7  94.9  70.6  31.4  24.4  65.4  96.9  100.0
25 clusters + FF3   4.3  99.7  94.8  71.2  30.5  23.3  66.0  96.6  100.0
25 clusters + FF5   4.3  99.7  94.5  70.2  30.2  23.7  64.4  96.5  100.0
30 clusters         4.5  99.7  94.9  71.0  31.4  25.0  65.5  96.9  100.0
30 clusters + FF3   4.4  99.7  94.6  70.3  31.0  23.7  65.4  96.6  100.0
30 clusters + FF5   4.3  99.7  94.5  69.7  30.6  23.8  64.4  96.6  100.0
35 clusters         4.7  99.7  94.9  70.6  31.9  23.9  65.7  97.0  100.0
35 clusters + FF3   4.5  99.7  94.7  70.0  31.4  23.1  65.4  96.7  100.0
35 clusters + FF5   4.7  99.7  94.5  69.8  30.7  23.6  65.2  96.4  100.0
40 clusters         5.0  99.7  95.0  70.6  31.7  24.3  65.1  96.5  100.0
40 clusters + FF3   4.7  99.7  95.2  70.1  29.9  23.5  65.0  96.5  100.0
40 clusters + FF5   4.5  99.7  94.7  69.7  30.4  24.0  64.6  96.2  100.0
50 clusters         4.1  99.7  95.0  71.0  31.4  24.7  66.0  96.9  100.0
50 clusters + FF3   4.2  99.7  94.9  70.7  30.4  24.1  65.1  96.6  100.0
50 clusters + FF5   4.0  99.7  94.7  70.1  30.6  24.0  64.9  96.4  100.0

In [10]:
results_df['KP']['γ=1']

                  0.0% -5.0% -2.0% -1.0% -0.5%  0.5%  1.0%  2.0%  5.0%
Market Model       6.0  99.5  95.1  69.0  29.7  26.0  67.8  96.6  99.5
FF3                4.9  99.6  98.3  85.7  43.3  37.9  84.1  98.5  99.6
FF5                4.9  99.6  98.3  85.7  42.8  39.3  84.2  98.6  99.6
5 clusters         5.2  99.6  98.5  86.4  44.1  39.6  84.6  98.7  99.6
5 clusters + FF3   5.7  99.6  98.6  87.4  45.9  40.7  85.4  98.9  99.6
5 clusters + FF5   4.7  99.6  98.6  87.8  45.8  40.7  85.6  98.8  99.6
10 clusters        5.0  99.6  98.7  87.4  44.8  39.6  84.9  99.0  99.6
10 clusters + FF3  5.2  99.6  98.6  88.0  46.2  41.5  85.1  98.9  99.6
10 clusters + FF5  5.1  99.6  98.6  88.0  45.7  41.7  85.4  98.8  99.6
15 clusters        5.2  99.6  98.6  87.9  45.5  40.9  85.5  98.9  99.6
15 clusters + FF3  5.5  99.6  98.6  88.0  47.0  42.2  85.6  98.8  99.6
15 clusters + FF5  5.1  99.6  98.6  88.4  46.3  41.9  86.0  98.8  99.6
20 clusters        5.1  99.6  98.7  87.3  45.5  41.4  85.0  98.8  99.6
20 clusters + FF3  5.2  99.6  98.6  88.2  47.0  42.2  85.4  98.8  99.6
20 clusters + FF5  5.3  99.6  98.6  88.2  46.2  41.9  85.2  98.8  99.6
25 clusters        5.0  99.6  98.6  87.7  46.2  40.9  85.2  99.0  99.6
25 clusters + FF3  4.9  99.6  98.7  88.1  48.0  41.2  85.6  98.9  99.6
25 clusters + FF5  5.1  99.6  98.6  87.7  46.8  40.9  86.2  98.9  99.6
30 clusters        5.1  99.6  98.6  87.6  45.9  41.1  85.5  99.0  99.6
30 clusters + FF3  5.0  99.6  98.5  88.3  46.8  41.3  85.8  99.0  99.6
30 clusters + FF5  4.7  99.6  98.5  88.2  46.2  41.8  86.2  98.9  99.6
35 clusters        5.1  99.6  98.7  88.1  46.6  41.0  86.5  98.8  99.6
35 clusters + FF3  4.8  99.6  98.6  87.9  48.3  41.8  85.5  98.9  99.6
35 clusters + FF5  5.0  99.6  98.5  88.1  47.0  41.8  86.4  98.9  99.6
40 clusters        5.0  99.6  98.6  88.1  46.3  41.1  86.4  98.9  99.6
40 clusters + FF3  5.0  99.6  98.6  88.6  46.9  42.5  85.7  99.0  99.6
40 clusters + FF5  5.0  99.6  98.5  88.5  46.3  41.8  85.7  98.9  99.6
50 clusters        4.9  99.6  98.6  88.2  47.0  41.2  85.7  98.8  99.6
50 clusters + FF3  5.2  99.6  98.6  88.1  47.3  42.6  86.0  99.1  99.6
50 clusters + FF5  5.4  99.6  98.6  88.4  46.2  41.9  86.3  98.9  99.6

In [11]:
results_df['CS']['γ=1']

                   0.0% -5.0% -2.0% -1.0% -0.5%  0.5%  1.0%  2.0%   5.0%
Market Model       13.2  99.8  93.1  66.4  34.0  30.2  62.9  95.0   99.9
FF3                 5.2  99.7  94.9  70.3  30.8  24.3  64.6  96.1   99.9
FF5                 5.2  99.7  94.7  69.8  30.6  25.0  64.4  96.0   99.9
5 clusters          4.7  99.7  94.8  70.7  31.6  25.2  65.4  96.5  100.0
5 clusters + FF3    4.2  99.7  94.5  70.7  30.4  23.8  65.4  96.2  100.0
5 clusters + FF5    4.0  99.7  94.7  70.1  30.5  23.6  65.2  96.1  100.0
10 clusters         4.7  99.7  94.9  71.2  31.4  24.7  65.2  96.6  100.0
10 clusters + FF3   4.6  99.7  94.9  70.8  30.4  23.4  65.4  96.6  100.0
10 clusters + FF5   4.2  99.7  94.8  69.9  30.7  23.7  65.0  96.4  100.0
15 clusters         4.5  99.7  95.0  70.5  31.7  24.8  65.3  96.9  100.0
15 clusters + FF3   4.1  99.7  94.8  70.5  30.6  23.9  65.4  96.4  100.0
15 clusters + FF5   4.2  99.7  94.6  70.4  30.9  23.8  64.7  96.3  100.0
20 clusters         4.1  99.7  94.9  70.9  31.8  23.8  65.7  96.9  100.0
20 clusters + FF3   3.9  99.7  94.7  70.8  30.2  24.2  65.5  96.6  100.0
20 clusters + FF5   3.7  99.7  94.7  70.1  30.4  24.4  64.7  96.8  100.0
25 clusters         4.9  99.7  94.9  70.6  31.4  24.4  65.4  96.9  100.0
25 clusters + FF3   4.3  99.7  94.8  71.2  30.5  23.3  66.0  96.6  100.0
25 clusters + FF5   4.3  99.7  94.5  70.2  30.2  23.7  64.4  96.5  100.0
30 clusters         4.5  99.7  94.9  71.0  31.4  25.0  65.5  96.9  100.0
30 clusters + FF3   4.4  99.7  94.6  70.3  31.0  23.7  65.4  96.6  100.0
30 clusters + FF5   4.3  99.7  94.5  69.7  30.6  23.8  64.4  96.6  100.0
35 clusters         4.7  99.7  94.9  70.6  31.9  23.9  65.7  97.0  100.0
35 clusters + FF3   4.5  99.7  94.7  70.0  31.4  23.1  65.4  96.7  100.0
35 clusters + FF5   4.7  99.7  94.5  69.8  30.7  23.6  65.2  96.4  100.0
40 clusters         5.0  99.7  95.0  70.6  31.7  24.3  65.1  96.5  100.0
40 clusters + FF3   4.7  99.7  95.2  70.1  29.9  23.5  65.0  96.5  100.0
40 clusters + FF5   4.5  99.7  94.7  69.7  30.4  24.0  64.6  96.2  100.0
50 clusters         4.1  99.7  95.0  71.0  31.4  24.7  66.0  96.9  100.0
50 clusters + FF3   4.2  99.7  94.9  70.7  30.4  24.1  65.1  96.6  100.0
50 clusters + FF5   4.0  99.7  94.7  70.1  30.6  24.0  64.9  96.4  100.0